sudo: required
language: python
python:
  - 3.7
os:
  - linux
install:
  - pip install flake8
  - pip install -r requirements/ci.txt
  - pip install coverage==4.5.4
script:
  - make cov
after_success:
  - coveralls